apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-go-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rminix/simple-go-app-deploy.git
    targetRevision: HEAD
    path: dev
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: project_name
          value: "test11"
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
